services:
  - type: web
    name: ddi-api
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install --python-version 3.11 -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: HF_TOKEN
        sync: false
      - key: HF_REPO
        value: VarshaSekar/Drug_Drug_Prediction
      - key: JWT_SECRET
        generateValue: true
    disk:
      name: model-cache
      mountPath: /tmp
      sizeGB: 1